security:

  providers:
    mysql_security_provider:
      entity:
        class: AppBundle:User

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false
    main:
      anonymous: ~
      guard:
        authenticators:
          - security.form_authenticator
      logout:
        path: /logout
        target: /login

  access_control:
    - { path: ^/admin, roles: ROLE_ADMIN }
    - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/reset/password, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/request/password/reset, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/authenticate/token, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
